import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const data = JSON.parse(fs.readFileSync(path.join(root, 'data/map.json'), 'utf8'));
const template = fs.readFileSync(path.join(root, 'src/template.html'), 'utf8');
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));
const route = rt => data.models.find(m => m.id === rt.m).full + ' · ' + data.labels[rt.r];
const trigger = change => change ? (change.m ? route(change) + ': ' : '') + change.when : 'No condition recorded.';
const headings = ['Task / environment', 'Starting point', 'Reason / note', 'Step up or change', 'Step down'];
const rows = Object.values(data.tasks).map(t => [
  t.title + ' (' + data.ENV[t.env] + ')',
  t.routes.map(route).join(' or '),
  t.why + (t.note ? ' ' + t.note : ''),
  trigger(t.up), trigger(t.down)
]);
const table = '<table class="ef-routing"><caption>All twelve task cases</caption><thead><tr>' +
  headings.map(h => '<th scope="col">' + escape(h) + '</th>').join('') + '</tr></thead><tbody>' +
  rows.map(row => '<tr>' + row.map((value, i) => i === 0 ? '<th scope="row">' + escape(value) + '</th>' : '<td>' + escape(value) + '</td>').join('') + '</tr>').join('') + '</tbody></table>';
const options = Object.entries(data.ENV).map(([env,label]) => '<optgroup label="' + escape(label) + '">' +
  Object.entries(data.tasks).filter(([,t]) => t.env === env).map(([id,t]) => '<option value="' + escape(id) + '">' + escape(t.title) + '</option>').join('') + '</optgroup>').join('');
let html = template.replace('/* MAP_DATA */', JSON.stringify(data).replace(/</g, '\\u003c')).replace('/* ROUTING_TABLE */', table).replace('/* TASK_OPTIONS */', options);
if (/\/\* (MAP_DATA|ROUTING_TABLE|TASK_OPTIONS) \*\//.test(html)) throw new Error('Unresolved build placeholder');
html = '<!-- Generated by scripts/build.mjs. Edit data/map.json or src/template.html. -->\n' + html;
const markdown = '# The twelve starting points\n\n' +
  'Generated from [the map data](../data/map.json). Travis’s September 2026 field study, not a model benchmark or a universal recommendation. Alternatives are equal starting points. No condition recorded means the original case did not supply one.\n\n' +
  Object.values(data.tasks).map(t => '## ' + t.title + '\n\n' +
    '**Environment:** ' + data.ENV[t.env] + '\n\n' +
    '**Start:** ' + t.routes.map(route).join(' or ') + '\n\n' + t.why + (t.note ? ' ' + t.note : '') + '\n\n' +
    '**Step up or change:** ' + trigger(t.up) + '\n\n**Step down:** ' + trigger(t.down) + '\n').join('\n') +
  '\n[How to compare settings](../evals/README.md) · [Sources and limits](SOURCES.md) · [Project home](../README.md)\n';
const outputs = [['site/index.html', html], ['docs/ROUTING.md', markdown]];
const check = process.argv.includes('--check');
for (const [name, content] of outputs) {
  const target = path.join(root, name);
  if (check) {
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) throw new Error(name + ' is stale; run node scripts/build.mjs');
  } else fs.writeFileSync(target, content);
}
console.log(check ? 'Generated files match their sources.' : 'Built portable HTML and complete text guide.');
